In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from matplotlib import style
style.use('ggplot')

In [3]:
data=pd.read_csv("Product.csv")
data.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
df = data.values
print(df.shape)

(400, 5)


In [5]:
X_sample=data.iloc[:,[2,3]].values
Y=data.iloc[:,4].values
print(X_sample.shape, Y.shape)

(400, 2) (400,)


In [6]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X_sample)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)
print(X_train.shape,Y_train.shape)
print(X_test.shape,Y_test.shape)

(320, 2) (320,)
(80, 2) (80,)


In [8]:
class svc:
    def __init__(self , C = 0.01 , n_iters = 100 , learning_rate = 0.1):
 
        self.c = C
        self.iter = n_iters
        self.eta = learning_rate
            
    def fit(self , x , y):
        self.x = x
        self.y = y
        
        w = np.zeros([1 , x.shape[1]])
        b = 0
        
        costs = np.zeros(self.iter)
        for i in range(self.iter):
            cost = x @ w.T + b
            b = b - self.eta * self.c * sum(cost - y) 
            w = w - self.eta * self.c * sum((cost - y)*x) 
            costs[i] = self.c * sum( (y * cost)  + (1 - y)*cost ) + (1/2)* sum(w.T**2)
        
        self.w = w
        self.b = b 
        self.costs = costs
        
    
    def predict(self , x_test):
        pred_y =  []
        svc = x_test @ self.w.T + self.b
        for i in svc:
            if i >= 0:
                pred_y.append(1)
            else:
                pred_y.append(0)
        
        return pred_y

In [9]:
Y = Y.reshape([len(Y) , 1])

In [10]:
algo = svc(learning_rate=0.001 , C = 0.01)
algo.fit(X , Y)

In [11]:
pred_y = algo.predict(X)

In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(Y , pred_y))

[[ 69 188]
 [  0 143]]


In [13]:
Y_train = Y_train.reshape([len(Y_train) , 1])
algo = svc(learning_rate = 0.001 , C = 0.01)
algo.fit(X_train , Y_train)
Y_bar = algo.predict(X_test)
print(confusion_matrix(Y_test , Y_bar))

[[11 32]
 [ 0 37]]


In [14]:
y_hat = algo.predict(X_train)
print(confusion_matrix(Y_train , y_hat))

[[ 61 153]
 [  0 106]]
